DONE deployment CD, keep last succeeded deployment as tag

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -56,7 +56,7 @@ jobs:
         run: npm install
 
       - name: Build
-        run: npm run build
+        run: npx vite build --mode staging
 
       - name: Deploy to staging and set BASE_URL
         env:
@@ -84,3 +84,69 @@ jobs:
         run: npm test
         env:
           BASE_URL: ${{env.BASE_URL}}
+
+  deploy-to-prod:
+    runs-on: ubuntu-latest
+    needs: deploy-to-staging
+    env:
+      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
+      VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
+      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
+      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "20"
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: Build
+        run: npx vite build --mode production
+
+      - name: Install Firebase CLI
+        run: npm install -g firebase-tools
+
+      - name: Deploy to production and set BASE_URL
+        run: |
+          firebase use hone-prod
+          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
+          DEPLOY_OUTPUT=$(firebase deploy --only hosting --token "$FIREBASE_TOKEN")
+          echo "$DEPLOY_OUTPUT"
+          HOSTING_URL=$(echo "$DEPLOY_OUTPUT" | grep -oP "https://[a-zA-Z0-9\-]+\.web\.app")
+          if [ -n "$HOSTING_URL" ]; then
+            echo "BASE_URL=$HOSTING_URL" >> $GITHUB_ENV
+          else
+            echo "BASE_URL is empty. Deployment failed." >&2
+            exit 1
+          fi
+
+      - name: Wait for Firebase deployment to be ready
+        run: npx wait-on $BASE_URL
+        env:
+          BASE_URL: ${{env.BASE_URL}}
+
+      - name: Run Tests
+        run: npm test
+        continue-on-error: true
+        env:
+          BASE_URL: ${{env.BASE_URL}}
+
+      - name: Git tag succeeded deployment
+        if: success()
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git tag -f succeeded-deployment
+          git push origin succeeded-deployment --force
+
+      - name: Disable staging deployment
+        run: |
+          firebase use hone-staging-0 --token $FIREBASE_TOKEN
+          firebase hosting:disable --force --token $FIREBASE_TOKEN
